Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/StringLiteralsInInterpolation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
